apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline
spec: 
  params: 
    - name: 
      type: 
  tasks:
    - name: 
      taskRef:
        name: 
      params:
        - name: 
          value: 
