apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-example-app
  namespace: argocd
  labels:
    name: flask-example-app
spec:
  project: flask-example
  source:
    repoURL: https://github.com/manoulas/flask-example.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: flask-example